---
title: "real-data"
author: "yws"
date: "2025-05-02"
output: html_document
---
```{r}
options(digits = 4)
library(GTtrans)
```

```{r}
D = read.csv("paper1_41598_2025_92709_MOESM2_ESM.csv")
D[is.na(D)] <- 0
```

```{r}
pi_1 = 1-0.0001
n_0 = 0
n_right = 0
for (i in unique(D$PoolID)){
  if(sum(D[D$PoolID == i,]$IndivResult<1000) == 3){
    n_0 = n_0+1
    if(sum(D[D$PoolID == i,]$PoolResult<40) == 3){
      n_right = n_right+1
    }
  }
}
print(n_right/n_0)
pi_0 = n_right/n_0
```


```{r}
set.seed(1234)
index = list()
p_tilde_data=c()
p_hat_data=c()
p_breve_data = c()

p_r_data = c()

for (i in 1:100){
  k = 3
  
  I = sample(unique(D$PoolID), floor(dim(D)[1]/3/20), replace = F)
  D_sample = D[D$PoolID %in% I,]
  d = matrix(D_sample$IndivResult,nrow = 3)
  index[[i]] = I
  m = dim(D_sample)[1]/3
  
  gresult = c()
  for (a in unique(D_sample$PoolID)){
    if(D_sample[D_sample$PoolID == a,]$PoolResult[1]>40){
      gresult = c(gresult,1)
    }else{
      gresult = c(gresult,0)
    }
  }
  m_1 = sum(gresult)
  
  m_1i=rep(0,k+1)
  retest=which(gresult==1)
  R=0
  S0 = 1
  S1 = 1
  for (r in retest){
    R=0
    for(d_1 in d[,r]){
      if(d_1>1000){
        R=R+rbinom(1,1,S1)
      }else{
        R=R+rbinom(1,1,1-S0)
      }
    }
    m_1i[R+1]=m_1i[R+1]+1
  }
  
  g_tilde=m_1/m
  p_tilde=1-((pi_1-min(pi_1,max(1-pi_0,g_tilde)))/(pi_0+pi_1-1))^(1/k)

  p_tilde_j = c(1019/21833,10/215)
  v_tilde_j = c(1019*(21833 - 1019)/(21833^3),10*(215-10)/(215^3))
  g_tilde_j = pi_1-(pi_0+pi_1-1)*(1-p_tilde_j)^k
  
  tran = GT_tran(m,k,pi_0,pi_1,m_1,p_tilde_j,v_tilde_j,w = 1,eta = NULL)
  tran_retest = GT_tran_retest(m,k,pi_0,pi_1,S0,S1,m_1,m_1i,p_tilde_j,v_tilde_j,w = 1,eta = NULL)
  
  p_tilde_data = c(p_tilde_data, p_tilde)
  p_hat_data = c(p_hat_data, tran$p_hat)
  p_breve_data = c(p_breve_data, tran_retest$p_breve)
  
}
print(paste('mean of p_tilde',signif(mean(p_tilde_data), 4)))
print(paste('mean of p_hat',signif(mean(p_hat_data), 4)))
print(paste('mean of p_breve',signif(mean(p_breve_data), 4)))

print(paste('variance of p_tilde',signif(var(p_tilde_data), 4)))
print(paste('variance of p_hat',signif(var(p_hat_data), 4)))
print(paste('variance of p_breve',signif(var(p_breve_data), 4)))

```
